model:
  type: 'RetinaNetResNet101'
  min_size: 600
  max_size: 1000

dataset:
  train: 'COCO'
  eval: 'COCO'
  n_fg_class: 80

solver:
  base_lr: 0.005  # 0.02 / 4
  n_iteration: 360000
  lr_step: [240000, 320000]

n_gpu: 2
n_sample_per_gpu: 2