model:
  type: 'RetinaNetResNet50'
  min_size: 600
  max_size: 999

dataset:
  train: 'VOC'
  val: 'VOC'
  n_fg_class: 20

solver:
  base_lr: 0.005  # 0.02 / 4
  n_iteration: 30000
  lr_step: [15000, 25000]

n_gpu: 2
n_sample_per_gpu: 2